
CREATE TABLE PARENT(
SSN CHAR(5) NOT NULL,
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50),
DOB DATE,
EMAIL VARCHAR(10),
CONTACTNO CHAR(10),
ADDRESS  VARCHAR(30),
ZIPCODE CHAR(5),
PRIMARY KEY(SSN));

CREATE TABLE TOYS(
T_ID INT NOT NULL,
TOY_NAME VARCHAR(20),
DATE_OF_PURCHASE DATE,
COMPANY VARCHAR(10),
TOTAL_QUANTITY INT,
PRIMARY KEY(T_ID));

CREATE TABLE FOOD(
F_ID INT NOT NULL,
FOOD_NAME VARCHAR(20),
PRICE INT,
QUANTITY INT,
PRIMARY KEY(F_ID));

CREATE TABLE JOB(
JOB_ID INT NOT NULL,
BASIC_SALARY INT,
PRIMARY KEY(JOB_ID));

CREATE TABLE DEPARTMENT(
DEPT_ID INT NOT NULL,
DEPT_NAME VARCHAR(20),
MGR_SSN CHAR(9),
PRIMARY KEY(DEPT_ID));

CREATE TABLE CARETAKER(
CSSN CHAR(5) NOT NULL,
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50),
DOB DATE,
EMAIL VARCHAR(10),
CONTACTNO CHAR(10),
JOBTYPE CHAR (1),
SUBJECT VARCHAR(20),
JOB_ID INT,
MGR_SSN CHAR(9),
DEPT_ID INT,
PRIMARY KEY(CSSN),
FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

ALTER TABLE CARETAKER ADD CONSTRAINT SUPERVISOR_KEY FOREIGN KEY (MGR_SSN) REFERENCES CARETAKER(CSSN);

ALTER TABLE DEPARTMENT ADD CONSTRAINT MGR_KEY FOREIGN KEY (MGR_SSN) REFERENCES CARETAKER(CSSN);

CREATE TABLE CLASSSECTION(
CLASS_ID INT NOT NULL,
ROOM VARCHAR(10),
LOCATION VARCHAR(20),
CLASS_TEACHER CHAR(9),
PRIMARY KEY(CLASS_ID),
FOREIGN KEY (CLASS_TEACHER) REFERENCES CARETAKER(CSSN));

CREATE TABLE CHILD(
CHILD_ID INT NOT NULL,
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50),
DOB DATE,
ENAME VARCHAR(10),
EPHONENO CHAR(10),
PSSN CHAR(9),
CLASS INT,
PRIMARY KEY (CHILD_ID),
FOREIGN KEY (PSSN) REFERENCES PARENT(SSN),
FOREIGN KEY (CLASS) REFERENCES CLASSSECTION(CLASS_ID));

CREATE TABLE TOY_DISTRIBUTION(
TOY_ID INT NOT NULL,
CLASS_ID INT NOT NULL,
QUANTITY INT,
FOREIGN KEY (TOY_ID) REFERENCES TOYS(T_ID),
FOREIGN KEY (CLASS_ID) REFERENCES CLASSSECTION(CLASS_ID));

CREATE TABLE TUITION_PAYMENT(
PAYMENT_ID INT NOT NULL,
PAYMENT_TYPE VARCHAR(20) NOT NULL,
PAYMENT_DATE DATE,
AMOUNT INT,
CHILD_ID INT,
PRIMARY KEY(PAYMENT_ID),
FOREIGN KEY (CHILD_ID) REFERENCES CHILD(CHILD_ID));

CREATE TABLE TIMING(
TIME_ID INT NOT NULL,
CSSN CHAR(9) NOT NULL,
TIMEIN TIMESTAMP,
TIMEOUT TIMESTAMP,
PRIMARY KEY(TIME_ID),
FOREIGN KEY (CSSN) REFERENCES CARETAKER(CSSN));

CREATE TABLE FOODORDEREDBY (
STAFFSSN CHAR(9) NOT NULL,
FOOD_ID INT NOT NULL,
DATEORDERED DATE,
FOREIGN KEY (STAFFSSN) REFERENCES CARETAKER(CSSN),
FOREIGN KEY (FOOD_ID) REFERENCES FOOD(F_ID));

CREATE TABLE FOODRECORD(
CHILD_ID INT NOT NULL,
FOOD_ID INT NOT NULL,
PRIMARY KEY(CHILD_ID,FOOD_ID),
FOREIGN KEY (CHILD_ID) REFERENCES CHILD(CHILD_ID),
FOREIGN KEY (FOOD_ID) REFERENCES FOOD(F_ID));

CREATE TABLE SALARYCOMPUTATION(
CARETAKERSSN CHAR(9) NOT NULL,
TIMINGID INT NOT NULL,
JOBID INT NOT NULL,
SALARY INT,
PRIMARY KEY(CARETAKERSSN,TIMINGID,JOBID),
FOREIGN KEY (CARETAKERSSN) REFERENCES CARETAKER(CSSN),
FOREIGN KEY (TIMINGID) REFERENCES TIMING(TIME_ID),
FOREIGN KEY (JOBID) REFERENCES JOB(JOB_ID));

